### ISSUE TITLE
Does anybody succeed to use the mels from Tactotron when synthesis?

### ISSUE THREAD

**Issue by hxs7709** [geneing/WaveRNN#2]
When I use mels from this tree https://github.com/Rayhane-mamah/Tacotron-2 during synthesis, it reports following error. 
Does anybody succeed to use the mels from Tactotron when synthesis?
Thank you.

// Error log
Traceback (most recent call last):
  File "mygenerate2.py", line 213, in <module>
    generate(step, data_root, 'my_outputs', test_ids)
  File "mygenerate2.py", line 143, in generate
    output = model.generate(mel)
  File "/mnt/data/hxs/WaveRNN_geneing_ljspeechall_2000epochs_tactIntegrate/models.py", line 163, in generate
    mels, aux = self.upsample(mels)
  File "/home/hxs/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/data/hxs/WaveRNN_geneing_ljspeechall_2000epochs_tactIntegrate/models.py", line 83, in forward
    aux = self.resnet(m).unsqueeze(1)
  File "/home/hxs/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/data/hxs/WaveRNN_geneing_ljspeechall_2000epochs_tactIntegrate/models.py", line 43, in forward
    x = self.conv_in(x)
  File "/home/hxs/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hxs/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 176, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [128, 80, 5], expected input[1, 103, 80] to have 80 channels, but got 103 channels instead

**Comment by geneing** [comment]
@hxs7709 Error message indicates that array mel is the wrong size. Since 80 is the typical number of mel dimensions, I think the last dimension and the one before last are swapped.  You should probably apply torch.transpose before calling generate function. 

I'm currently working with two other people on a batch generation approach that can generate sound at real time speed or faster. The work is done in https://github.com/geneing/WaveRNN-Pytorch repo in a model_simplification branch. Once I'm done optimizing the vocoder (in a couple of weeks), I'm planning on adding tacotron2 code for end-to-end generation.

**Comment by hxs7709** [comment]
@geneing Thank you very much for sharing it.
Yes, the array from Tactotron2's npy need to be swapped.
Also, the parameters and methods to generate mels seems a little different between this WaveRNN(dsp.py) and Tacotron2(audio.py). We need to adapt them to use the same way, so that tacotron2 and WaveRNN can be integrated as an end-to-end generation.
Please help to correct me if any wrong understanding.

**Comment by hxs7709** [comment]
@geneing For your new tree https://github.com/geneing/WaveRNN-Pytorch, the synthesis speed (1200 samples/sec) is almost similar as this tree (1050 samples/sec). I test them in the same environment. What is the speed improvement observed in your test?

Also, the quality of synthesized audio with this tree should be better.

**Comment by geneing** [comment]
@hxs7709 The new branch now contains 2 improvements. 1. Pruning code that can remove up to 85% of the weigthts in RNN and post-net FC layers. 2. Optimized C++ library that uses pruned weights and can generate at close to real time speed. I'm actively working on the new branch, trying to find the best balance between quality and speed.
